#!/usr/bin/env node
/* eslint-disable no-await-in-loop */
// Records every package's public API in a committed report, and fails when the
// built surface no longer matches it.
//
// Package versions say a release is breaking; nothing said *what* broke. A
// removed export, a narrowed parameter, or a widened return type all ship
// silently today, and a reviewer has to infer them from the diff of the
// implementation. The report makes the surface itself reviewable: a pull
// request that changes it must change this file too, which is the moment to ask
// whether the changeset says so.
//
// Reports are generated from the built `.d.ts`, re-printed through the
// TypeScript printer and sorted by name, so they are stable against the
// emitter's formatting and only move when the API actually moves.
//
// Run `pnpm run api-report:update` to accept an intended change.
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";

import ts from "typescript";

import { packagesDir, rootDir } from "./lib/smoke.ts";

const reportDir = join(rootDir, "api-report");
const shouldWrite = process.argv.includes("--write");
const packages = await readPublicPackages();
const problems = [];
let checked = 0;

await mkdir(reportDir, { recursive: true });

for (const pkg of packages) {
  const report = renderReport(pkg);
  const reportPath = join(reportDir, `${pkg.name.replace("@coexist/", "")}.api.md`);
  const existing = await readIfPresent(reportPath);

  if (shouldWrite) {
    await writeFile(reportPath, report);
    checked += 1;
    continue;
  }

  if (existing === undefined) {
    problems.push(
      `${pkg.name} has no API report. Run \`pnpm run api-report:update\` and commit ` +
        `${relative(rootDir, reportPath)}.`,
    );
    continue;
  }

  if (existing !== report) {
    problems.push(
      `${pkg.name}'s public API no longer matches ${relative(rootDir, reportPath)}.\n` +
        `${describeDrift(existing, report)}\n` +
        "Run `pnpm run api-report:update` and review the diff: an intended change needs a " +
        "changeset saying so, and a removal or narrowing is breaking.",
    );
    continue;
  }

  checked += 1;
}

if (problems.length > 0) {
  throw new Error(`Public API report is out of date.\n\n${problems.join("\n\n")}`);
}

console.log(
  shouldWrite
    ? `Wrote ${checked} API report(s) to ${relative(rootDir, reportDir)}.`
    : `Verified ${checked} package API report(s).`,
);

async function readPublicPackages() {
  const entries = await readdir(packagesDir, { withFileTypes: true });
  const found = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) {
      continue;
    }

    const dir = join(packagesDir, entry.name);
    const packageJson = JSON.parse(await readFile(join(dir, "package.json"), "utf8"));

    if (packageJson.private === true) {
      continue;
    }

    const entryPoints = readTypeEntryPoints(dir, packageJson);

    if (entryPoints.length === 0) {
      throw new Error(`${packageJson.name} exposes no type entry point to report on.`);
    }

    found.push({ dir, entryPoints, name: packageJson.name });
  }

  return found.toSorted((left, right) => left.name.localeCompare(right.name));
}

/** Every `exports` subpath that ships types, so a subpath API is reported too. */
function readTypeEntryPoints(dir, packageJson) {
  const entryPoints = [];

  for (const [subpath, target] of Object.entries(packageJson.exports ?? {})) {
    const types = typeof target === "string" ? undefined : target?.types;

    if (typeof types === "string") {
      entryPoints.push({ path: join(dir, types), subpath });
    }
  }

  return entryPoints.toSorted((left, right) => left.subpath.localeCompare(right.subpath));
}

function renderReport(pkg) {
  const lines = [
    `# ${pkg.name} public API`,
    "",
    "<!-- Generated by `pnpm run api-report:update`. Review changes here as API changes. -->",
  ];

  for (const entryPoint of pkg.entryPoints) {
    lines.push(
      "",
      `## ${entryPoint.subpath === "." ? pkg.name : `${pkg.name}/${entryPoint.subpath.slice(2)}`}`,
      "",
      "```ts",
      ...renderEntryPoint(entryPoint.path),
      "```",
    );
  }

  return `${lines.join("\n")}\n`;
}

function renderEntryPoint(entryPath) {
  const program = ts.createProgram([entryPath], {
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    noEmit: true,
    skipLibCheck: true,
    strict: true,
    target: ts.ScriptTarget.ES2022,
  });
  const checker = program.getTypeChecker();
  const sourceFile = program.getSourceFile(entryPath);

  if (sourceFile === undefined) {
    throw new Error(`Could not load ${entryPath}. Run \`pnpm run build\` first.`);
  }

  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);

  if (moduleSymbol === undefined) {
    throw new Error(`${entryPath} exports nothing.`);
  }

  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed, removeComments: true });
  const rendered = [];
  const exportedDeclarations = new Set();

  for (const exported of checker
    .getExportsOfModule(moduleSymbol)
    .toSorted((left, right) => left.getName().localeCompare(right.getName()))) {
    // An entry point re-exports through `export { … }`, so the export symbol is
    // an alias whose declaration is the specifier, not the shape it names.
    const symbol =
      (exported.flags & ts.SymbolFlags.Alias) === 0 ? exported : checker.getAliasedSymbol(exported);
    const declarations = symbol.getDeclarations() ?? [];

    if (declarations.length === 0) {
      rendered.push(`// ${exported.getName()}: no declaration resolved`);
      continue;
    }

    for (const declaration of declarations) {
      exportedDeclarations.add(declaration);
      rendered.push(printDeclaration(printer, declaration, exported.getName()));
    }
  }

  // An exported declaration can be shaped by a type the package never exports —
  // `ClassProvideOptions extends ProviderOptionsBase`, `DefineModuleOptions`
  // built from `ModuleMethodKey`. Rendering only the exports would let a change
  // to one of those alter every signature that inherits from it with nothing in
  // this file to review, which is the guarantee the report exists to make.
  const supporting = collectSupportingDeclarations(
    checker,
    exportedDeclarations,
    dirname(entryPath),
  );

  if (supporting.length > 0) {
    rendered.push(
      "",
      "// Not exported. Reachable from the surface above, so a change here is an API change.",
    );

    for (const declaration of supporting) {
      rendered.push(printDeclaration(printer, declaration, nameOfDeclaration(declaration)));
    }
  }

  return rendered;
}

/**
 * The type declarations an exported one reaches, restricted to this package's
 * own build. A type from a dependency cannot be inlined and is left as the bare
 * name it already prints as; one from `node_modules` or `lib.d.ts` is not this
 * package's API to report.
 */
function collectSupportingDeclarations(checker, exportedDeclarations, distDir) {
  const collected = new Map();
  const queue = [...exportedDeclarations];

  while (queue.length > 0) {
    const declaration = queue.shift();

    const visit = (node) => {
      if (ts.isIdentifier(node)) {
        for (const referenced of typeDeclarationsOf(checker, node, distDir)) {
          const name = nameOfDeclaration(referenced);

          if (
            name !== undefined &&
            !exportedDeclarations.has(referenced) &&
            !collected.has(referenced)
          ) {
            collected.set(referenced, name);
            queue.push(referenced);
          }
        }
      }

      ts.forEachChild(node, visit);
    };

    ts.forEachChild(declaration, visit);
  }

  return [...collected.keys()].toSorted((left, right) =>
    collected.get(left).localeCompare(collected.get(right)),
  );
}

function typeDeclarationsOf(checker, identifier, distDir) {
  let symbol = checker.getSymbolAtLocation(identifier);

  if (symbol === undefined) {
    return [];
  }

  if ((symbol.flags & ts.SymbolFlags.Alias) !== 0) {
    symbol = checker.getAliasedSymbol(symbol);
  }

  return (symbol.getDeclarations() ?? []).filter(
    (declaration) =>
      // Property and parameter names resolve to symbols too; only a type's own
      // declaration describes a shape worth reporting.
      (ts.isInterfaceDeclaration(declaration) ||
        ts.isTypeAliasDeclaration(declaration) ||
        ts.isEnumDeclaration(declaration) ||
        ts.isClassDeclaration(declaration)) &&
      declaration.getSourceFile().fileName.startsWith(`${distDir}/`),
  );
}

function nameOfDeclaration(declaration) {
  return ts.isVariableDeclaration(declaration) || declaration.name === undefined
    ? undefined
    : declaration.name.getText();
}

/**
 * Prints one declaration through the TypeScript printer so the report reflects
 * the shape, not the emitter's line breaks. Function bodies never appear in a
 * `.d.ts`, so a signature prints as a single readable line.
 */
function printDeclaration(printer, declaration, name) {
  const sourceFile = declaration.getSourceFile();

  if (ts.isVariableDeclaration(declaration)) {
    const statement = declaration.parent.parent;
    const kind = statement.declarationList.flags & ts.NodeFlags.Const ? "const" : "let";

    return `declare ${kind} ${printer.printNode(ts.EmitHint.Unspecified, declaration, sourceFile)};`;
  }

  const text = printer.printNode(ts.EmitHint.Unspecified, declaration, sourceFile);

  // A re-exported alias prints as its import clause, which says nothing about
  // the shape; name it instead of emitting noise.
  return text.startsWith("import ") ? `export { ${name} };` : text;
}

function describeDrift(existing, next) {
  const existingLines = new Set(existing.split("\n"));
  const nextLines = new Set(next.split("\n"));
  const removed = [...existingLines].filter((line) => line.trim() !== "" && !nextLines.has(line));
  const added = [...nextLines].filter((line) => line.trim() !== "" && !existingLines.has(line));
  const summary = [];

  for (const line of removed.slice(0, 10)) {
    summary.push(`  - ${line.trim()}`);
  }

  for (const line of added.slice(0, 10)) {
    summary.push(`  + ${line.trim()}`);
  }

  if (removed.length + added.length > 20) {
    summary.push(`  … and ${removed.length + added.length - 20} more line(s)`);
  }

  return summary.join("\n");
}

async function readIfPresent(path) {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") {
      return undefined;
    }

    throw error;
  }
}
